### PR TITLE
Refactor Calendar View into Multiple Widgets

### LINKED ISSUE #50: Split Calendar page into multiple widgets
Calendar Page is implemented as a single file currently, however is it possible to split it into multiple reusable widgets for decoupling, improving code writting and reusability

### PR DESCRIPTION
**Pull request by jsurrea**
I followed the approach used by [MeditoApp](https://github.com/meditohq/medito-app) to organize page-specific widgets. I moved all the independent components of Calendar Page into a new `widgets` directory and checked that the app behaves correctly.

### CODE REVIEW

**Comment by jsurrea** [comment]
@iGotty @SnowArtz what do you think about this approach? We could use it for the other pages that may incur in technical debt

**Review by iGotty — APPROVED** [review]
I like the idea!

**Comment by iGotty** [comment]
@jsurrea do you happen to know why the IconButton of Bars.svg no longer works? i.e. the slide-out menu no longer appears after implementing the refactoring

**Comment by jsurrea** [comment]
I do not know. I will open an issue to take a look at it

**Pull request merged**
